name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Debug repository structure
        run: |
          ls -la knowledge/ || echo "knowledge directory not found"
          ls -la experience/cli/ || echo "cli directory not found"
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: stable
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
          workdir: experience/cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}